#!/usr/bin/env python3
"""Generate Unicode 17 default case mappings and SIMD byte transforms from the UCD."""

import argparse
import bisect
import collections
import hashlib
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FAMILIES = {
    "greek_basic": [bytes([0xCE]), bytes([0xCF])],
    "latin1": [bytes([0xC2]), bytes([0xC3])],
    "latin": [bytes([b]) for b in range(0xC2, 0xC7)] + [bytes([0xE1, b]) for b in range(0xB8, 0xBC)],
    "cyrillic": [bytes([b]) for b in range(0xD0, 0xD4)],
    "greek": [bytes([b]) for b in (0xCE, 0xCF)] + [bytes([0xE1, b]) for b in range(0xBC, 0xC0)],
    "georgian": [bytes([0xE1, b]) for b in (0x82, 0x83, 0xB2, 0xB3)] + [bytes([0xE2, 0xB4])],
    "armenian": [bytes([b]) for b in range(0xD4, 0xD7)],
    "fullwidth": [bytes([0xEF, b]) for b in (0xBC, 0xBD)],
}


def load(ucd):
    maps = {"lower": {}, "upper": {}}
    for line in (ucd / "UnicodeData.txt").read_text().splitlines():
        f = line.split(";")
        cp = int(f[0], 16)
        for mode, column in [("lower", 13), ("upper", 12)]:
            if f[column]:
                maps[mode][cp] = (int(f[column], 16),)
    special = (ucd / "SpecialCasing.txt").read_text()
    assert "SpecialCasing-17.0.0.txt" in special
    for line in special.splitlines():
        line = line.split("#")[0].strip()
        if not line:
            continue
        f = [x.strip() for x in line.split(";")]
        if f[4]:
            assert f[4] == "Final_Sigma" or f[4].split()[0] in ("tr", "az", "lt"), f[4]
            continue
        for mode, column in [("lower", 1), ("upper", 3)]:
            maps[mode][int(f[0], 16)] = tuple(int(x, 16) for x in f[column].split())
    for mode, mapping in maps.items():
        maps[mode] = {cp: out for cp, out in mapping.items() if out != (cp,)}
        assert max(len("".join(map(chr, out)).encode()) / len(chr(cp).encode()) for cp, out in maps[mode].items()) <= 3
    properties = collections.defaultdict(list)
    text = (ucd / "DerivedCoreProperties.txt").read_text()
    assert "DerivedCoreProperties-17.0.0.txt" in text
    for line in text.splitlines():
        line = line.split("#")[0].strip()
        if not line:
            continue
        f = [x.strip() for x in line.split(";")]
        if f[1] not in ("Cased", "Case_Ignorable"):
            continue
        ends = f[0].split("..")
        properties[f[1]].append((int(ends[0], 16), int(ends[-1], 16)))
    return maps, properties


def runs(values):
    values = sorted(values)
    result = []
    i = 0
    while i < len(values):
        first = last = values[i]
        step = values[i + 1] - first if i + 1 < len(values) else 1
        if step not in (1, 2):
            step = 1
        i += 1
        while i < len(values) and values[i] == last + step:
            last = values[i]
            i += 1
        result.append((first, last, step))
    return result


def tables(maps, props, ucd):
    out = [
        "/* Generated by tools/generate_utf8_case.py from Unicode 17.0.0. See UNICODE-LICENSE.txt. */",
        "#ifndef STRINGZILLA_UTF8_CASE_TABLES_H_",
        "#define STRINGZILLA_UTF8_CASE_TABLES_H_",
        '#include "stringzilla/types.h"',
        (
            "typedef struct sz_unicode_case_mapping_t "
            "{ sz_rune_t first, last; sz_u8_t step, count; sz_i32_t values[3]; } sz_unicode_case_mapping_t;"
        ),
        "typedef struct sz_unicode_case_range_t { sz_rune_t first, last; } sz_unicode_case_range_t;",
    ]
    for filename in ("UnicodeData.txt", "SpecialCasing.txt", "DerivedCoreProperties.txt"):
        out.append("/* " + filename + " SHA256: " + hashlib.sha256((ucd / filename).read_bytes()).hexdigest() + " */")
    for mode, mapping in maps.items():
        entries = sorted(mapping.items())
        i = 0
        range_starts = []
        out.append(f"static sz_unicode_case_mapping_t const sz_unicode_{mode}_mappings_[] = {{")
        while i < len(entries):
            cp, target = entries[i]
            first = last = cp
            step = 1
            i += 1
            range_starts.append(cp)
            if len(target) == 1:
                delta = target[0] - cp
                if i < len(entries) and entries[i][0] - cp in (1, 2):
                    step = entries[i][0] - cp
                while i < len(entries) and entries[i][0] == last + step and entries[i][1] == (last + step + delta,):
                    last = entries[i][0]
                    i += 1
                values = [delta, 0, 0]
            else:
                values = list(target) + [0] * (3 - len(target))
            out.append(f"    {{0x{first:X}, 0x{last:X}, {step}, {len(target)}, {{{', '.join(map(str, values))}}}}},")
        out.append("};")
        out.append(f"static sz_u16_t const sz_unicode_{mode}_pages_[] = {{")
        for page in range((entries[-1][0] >> 8) + 2):
            out.append(f"    {bisect.bisect_left(range_starts, page << 8)},")
        out.append("};")
    for name, intervals in props.items():
        merged = []
        for lo, hi in sorted(intervals):
            if merged and lo <= merged[-1][1] + 1:
                merged[-1] = (merged[-1][0], max(hi, merged[-1][1]))
            else:
                merged.append((lo, hi))
        out.append(f"static sz_unicode_case_range_t const sz_unicode_{name.lower()}_ranges_[] = {{")
        out += [f"    {{0x{lo:X}, 0x{hi:X}}}," for lo, hi in merged]
        out.append("};")
    for mode in ("lower", "upper"):
        flags = [0] * 32
        e1_flags = [0] * 64
        for cp, mapped in maps[mode].items():
            source = chr(cp).encode()
            target = "".join(map(chr, mapped)).encode()
            if len(source) == len(target) and not (mode == "lower" and cp == 0x3A3):
                continue
            if len(source) == 2:
                flags[source[0] - 0xC0] |= 1 << (source[1] & 63)
            elif len(source) == 3 and source[0] == 0xE1:
                e1_flags[source[1] & 63] |= 1 << (source[2] & 63)
        out.append(f"static sz_u64_t const sz_unicode_{mode}_two_byte_irregular_[] = {{")
        out += [f"    0x{v:016X}ull," for v in flags]
        out.append("};")
        out.append(f"static sz_u64_t const sz_unicode_{mode}_e1_irregular_[] = {{")
        out += [f"    0x{v:016X}ull," for v in e1_flags]
        out.append("};")
    out.append("#endif")
    return "\n".join(out) + "\n"


class SIMD:
    def __init__(self, isa):
        self.isa = isa
        self.avx2 = isa == "haswell"
        self.width = 32 if self.avx2 else 64
        self.v = "__m256i" if self.avx2 else "__m512i"
        self.m = "__m256i" if self.avx2 else "sz_u64_t"
        self.bits = "sz_u32_t" if self.avx2 else "sz_u64_t"

    def both(self, a, b):
        return f"_mm256_and_si256({a}, {b})" if self.avx2 else f"({a} & {b})"

    def either(self, items):
        if not items:
            return "_mm256_setzero_si256()" if self.avx2 else "0"
        s = items[0]
        for b in items[1:]:
            s = f"_mm256_or_si256({s}, {b})" if self.avx2 else f"({s} | {b})"
        return s

    def select(self, values):
        parts = []
        for lo, hi, step in runs(values):
            if lo == hi:
                s = (
                    f"_mm256_cmpeq_epi8(v, _mm256_set1_epi8((char){lo}))"
                    if self.avx2
                    else f"_mm512_cmpeq_epi8_mask(v, _mm512_set1_epi8((char){lo}))"
                )
            else:
                s = (
                    f"sz_haswell_in_byte_range_(v, {lo}, {hi - lo + 1})"
                    if self.avx2
                    else f"_mm512_cmplt_epu8_mask(_mm512_sub_epi8(v, _mm512_set1_epi8((char){lo})), "
                    f"_mm512_set1_epi8({hi - lo + 1}))"
                )
            if step == 2:
                parity = (
                    f"_mm256_cmpeq_epi8(_mm256_and_si256(v, _mm256_set1_epi8(1)), _mm256_set1_epi8({lo & 1}))"
                    if self.avx2
                    else f"_mm512_cmpeq_epi8_mask(_mm512_and_si512(v, _mm512_set1_epi8(1)), _mm512_set1_epi8({lo & 1}))"
                )
                s = self.both(s, parity)
            parts.append(s)
        return self.either(parts)

    def mask(self, expr):
        return f"(sz_u32_t)_mm256_movemask_epi8({expr})" if self.avx2 else expr

    def prefix(self, prefix):
        name = "p" + prefix.hex()
        parts = []
        for back, b in enumerate(reversed(prefix), 1):
            parts.append(
                f"_mm256_cmpeq_epi8(prev{back}, _mm256_set1_epi8((char){b}))"
                if self.avx2
                else f"(_mm512_cmpeq_epi8_mask(v, _mm512_set1_epi8((char){b})) << {back})"
            )
        return name, self.both(self.either([]) if not parts else self.and_all(parts), "continuations")

    def and_all(self, items):
        s = items[0]
        for b in items[1:]:
            s = self.both(s, b)
        return s

    def family(self, mode, mapping, family, prefixes):
        o = [
            (
                f"SZ_HELPER_AUTO sz_size_t sz_utf8_{mode}_{self.isa}_{family}_({self.v} v, sz_ptr_t "
                f"target, sz_size_t available) {{"
            )
        ]
        if self.avx2:
            o += ["    __m256i prev1 = sz_haswell_previous_bytes_(v, 1);"]
            if any(len(p) == 2 for p in prefixes):
                o += ["    __m256i prev2 = sz_haswell_previous_bytes_(v, 2);"]
            o += [
                "    __m256i continuations = sz_haswell_in_byte_range_(v, 0x80, 0x40);",
                "    sz_u32_t allowed = ~(sz_u32_t)_mm256_movemask_epi8(v);",
            ]
        else:
            o += [
                (
                    "    sz_u64_t continuations = _mm512_cmplt_epu8_mask(_mm512_sub_epi8(v, "
                    "_mm512_set1_epi8((char)0x80)), _mm512_set1_epi8(0x40));"
                ),
                "    sz_u64_t allowed = ~(sz_u64_t)_mm512_movepi8_mask(v);",
            ]
        o += [f"    {self.bits} stop = 0;"]
        groups = collections.defaultdict(list)
        for prefix in prefixes:
            name, expr = self.prefix(prefix)
            o += [
                f"    {self.m} {name} = {expr};",
                f"    {self.bits} {name}_bits = {self.mask(name)};",
                "    allowed |= " + " | ".join([f"({name}_bits >> {j})" for j in range(len(prefix) + 1)]) + ";",
            ]
            special = []
            delta_groups = collections.defaultdict(list)
            for b in range(0x80, 0xC0):
                raw = prefix + bytes([b])
                cp = ord(raw.decode())
                value = "".join(map(chr, mapping.get(cp, (cp,)))).encode()
                if len(raw) != len(value) or (mode == "lower" and cp == 0x3A3):
                    special.append(b)
                elif raw != value:
                    delta_groups[tuple((y - x) % 256 for x, y in zip(raw, value))].append(b)
            if special:
                o += [f"    stop |= ({self.mask(self.both(name, self.select(special)))}) >> {len(prefix)};"]
            for deltas, vals in delta_groups.items():
                groups[deltas].append(self.both(name, self.select(vals)))
        o += [
            "    stop |= ~allowed | ~sz_u64_mask_until_(available);" if not self.avx2 else "    sz_unused_(available);",
            "    stop |= ~allowed;",
            f"    sz_size_t length = stop ? (sz_size_t)_tzcnt_u{self.width}(stop) : {self.width};",
            "    if (!length) return 0;",
            (
                f"    {self.v} result = sz_utf8_case_{self.isa}_ascii_(v, "
                f"{'sz_true_k' if mode == 'upper' else 'sz_false_k'});"
            ),
        ]
        for idx, (deltas, masks) in enumerate(groups.items()):
            o += [f"    {self.m} match{idx} = {self.either(masks)};"]
            for bytepos, delta in enumerate(reversed(deltas)):
                if not delta:
                    continue
                if self.avx2:
                    mask = f"match{idx}"
                    for j in range(bytepos):
                        mask = f"sz_haswell_next_bytes_({mask})"
                    o += [
                        (
                            f"    result = _mm256_add_epi8(result, _mm256_and_si256({mask}, "
                            f"_mm256_set1_epi8((char){delta})));"
                        )
                    ]
                else:
                    o += [
                        (
                            f"    result = _mm512_mask_add_epi8(result, match{idx} >> {bytepos}, result, "
                            f"_mm512_set1_epi8((char){delta}));"
                        )
                    ]
        if self.avx2:
            o += ["    _mm256_storeu_si256((__m256i *)target, result);"]
        else:
            o += ["    _mm512_mask_storeu_epi8(target, sz_u64_mask_until_(length), result);"]
        o += ["    return length;", "}"]
        return "\n".join(o)


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--ucd-dir", type=Path, required=True)
    p.add_argument("--clang-format", default="clang-format")
    args = p.parse_args()
    maps, props = load(args.ucd_dir)
    dest = ROOT / "include/stringzilla/utf8_case"
    dest.mkdir(exist_ok=True)
    (dest / "tables.h").write_text(tables(maps, props, args.ucd_dir))
    for isa in ("haswell", "icelake"):
        simd = SIMD(isa)
        text = "/* Generated Unicode 17 byte transforms. See UNICODE-LICENSE.txt. */\n"
        text += (
            f"#ifndef STRINGZILLA_UTF8_CASE_{isa.upper()}_MAPPINGS_H_\n#define "
            f"STRINGZILLA_UTF8_CASE_{isa.upper()}_MAPPINGS_H_\n"
        )
        for mode, mp in maps.items():
            for family, prefixes in FAMILIES.items():
                text += simd.family(mode, mp, family, prefixes) + "\n"
        text += "#endif\n"
        (dest / f"{isa}_mappings.h").write_text(text)
    subprocess.run(
        [
            args.clang_format,
            "--Wno-error=unknown",
            "-i",
            str(dest / "tables.h"),
            str(dest / "haswell_mappings.h"),
            str(dest / "icelake_mappings.h"),
        ],
        check=True,
    )
    print("Generated Unicode 17 serial tables and AVX2/AVX512 transforms.")


if __name__ == "__main__":
    main()
